heat_template_version: 2016-04-08
description: Deployment Description for PostgreSQL-HA Standby-Node (Script 5/5)

parameters:

  image_id:
    type: string
    description: Image used for servers
    default: ubuntu-xenial-16.04_lastest
  key_name:
    type: string
    description: SSH key to connect to the servers
  flavor:
    type: string
    description: flavor used by the servers
  availability_zone:
    type: string
    description: The Availability Zone to launch the instance.
  server_group:
    type: string
    description: server group of the nodes.

  standby_hostname:
    type: string
    description: Hostname of standby node.
  standby_volume_id:
    type: string
    description: ID of the pre-created volume to be attached to the node.
  standby_port:
    type: string
    description: Network port used by the node.
  standby_ip:
    type: string
    description: IP of standby node.

  service_db:
    type: string
    description: Name of the Database.
  admin_user:
    type: string
    description: Admin user for the service.
  admin_password:
    type: string
    hidden: true
    description: Password for the service_user password.

  primary_ip:
    type: string
    description: IP of primary vm.

resources:

  volume_attachment_standby:
    type: OS::Cinder::VolumeAttachment
    properties:
      volume_id: { get_param: standby_volume_id }
      instance_uuid: { get_resource: standby_server }
      mountpoint: /dev/vdb

  standby_server:
    type: OS::Nova::Server
    properties:
      flavor: {get_param: flavor}
      image: {get_param: image_id}
      availability_zone: { get_param: availability_zone }
      key_name: {get_param: key_name}
      scheduler_hints:
        group: {get_param: server_group}
      name: { get_param: standby_hostname }
      networks:
      - port: {get_param: standby_port }
      user_data_format: RAW
      user_data:
        str_replace:
          template: |
            #!/bin/bash
            mkdir -p /data
            echo "/dev/vdb       /data       ext4    defaults     0 0" >> /etc/fstab
            mkfs.ext4 /dev/vdb
            mount -a

            export REPOSITORY_POSTGRESQL="https://bitbucket.org/meshstack/deployment-scripts-postgresql/raw/HEAD/postgresql"
            export REPOSITORY_MONIT="https://bitbucket.org/meshstack/deployment-scripts-monit/raw/HEAD/monit"
            export REPOSITORY_POSTGRESQL_HA="https://bitbucket.org/meshstack/deployment-scripts-postgresql/raw/HEAD/postgresql/cluster"


            wget $REPOSITORY_POSTGRESQL/postgresql-template.sh --no-cache

            chmod +x postgresql-template.sh

            ./postgresql-template.sh -u $admin_user -p $admin_password -d $service_db -e openstack


            wget $REPOSITORY_POSTGRESQL_HA/postgresql-HA-template.sh --no-cache

            chmod +x postgresql-HA-template.sh

            ./postgresql-HA-template.sh -u $admin_user -p $admin_password -d $service_db -e openstack -i $primary_ip -j $standby_ip -a standby

          params:
            $service_db: {get_param: service_db}
            $admin_user: {get_param: admin_user}
            $admin_password: {get_param: admin_password}
            $primary_ip: {get_param: primary_ip}
            $standby_ip: {get_param: standby_ip}

outputs:
  ip:
    value: { get_attr: [ standby_server, first_address ]}
  vm:
    value: { get_resource: standby_server }
