---
# https://bosh.io/docs/cli-v2.html#deployment-mgmt

name: osb-bosh-postgresql

releases:
- name: osb-bosh-postgresql
  version: latest
- name: prometheus
  version: latest

update:
  canaries: 1
  max_in_flight: 2
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

variables:
- name: transport_ssh
  type: ssh
- name: pcp_password
  type: password
- name: ssl_ca
  type: certificate
  options:
    is_ca: true
    common_name: postgres-ssl

instance_groups:
- name: postgres
  instances: 2
  vm_type: small
  stemcell: default
  azs:
  - z1
  networks:
  - name: service
  persistent_disk_type: 10GB
  jobs:
  - name: postgres
    release: osb-bosh-postgresql-tde
  - name: backup-agent
    release: osb-bosh-postgresql-tde
  - name: postgres_exporter
    release: prometheus
    properties:
  properties:
    postgres_exporter:
      datasource_name: "postgresql://((exporter_credentials.username)):((exporter_credentials.password))@localhost:5432/postgres?sslmode=verify-full"
    backup_agent:
      username: backup
      password: rulez
    postgres:
      tde:
        key: ((tde_key))
      ssl:
        enabled: true
        ca: ((ssl_ca.certificate))((ssl_ca.ca))
        cakey: ((ssl_ca.private_key))
      resource:
        shared_buffers: 128MB
        temp_buffers: 8MB
        encoding:
          lc_messages: 'en_US.UTF-8'
          lc_monetary: 'en_US.UTF-8'
          lc_numeric:  'en_US.UTF-8'
          lc_time:     'en_US.UTF-8'
      config:
        port: 5432
        max_connections: 400
        max_files_per_process: 1000
        shared_preload_libraries: 'pg_stat_statements'
      archive_cleanup:
        threshold: 10
      hba:
        - host all all 0.0.0.0/0 md5
        - host all all ::/0 md5
      replication:
        archive_mode: 'on'
        enabled: true
        password: replication_rulez
      admin_users:
      - username: admin
        password: rulez
        admin: true
      - username: exporter
        password: rulez
        admin: false
      backup_users:
      - username: backup
        password: rulez
      users:
      - username: sample
        password: rulez
        admin: true
      databases:
      - name: sample
        users:
        - sample
        extensions:
        - citext
    ssh:
      pubkey: ((transport_ssh.public_key))
      privkey: ((transport_ssh.private_key))

