---
# https://bosh.io/docs/cli-v2.html#deployment-mgmt

name: osb-bosh-postgresql

releases:
- name: osb-bosh-postgresql
  version: latest
- name: prometheus
  version: latest

update:
  canaries: 1
  max_in_flight: 2
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

variables:
- name: transport_ssh
  type: ssh
- name: pcp_password
  type: password

instance_groups:
- name: postgres
  instances: 2
  vm_type: small
  stemcell: default
  azs:
  - z1
  networks:
  - name: service
  persistent_disk_type: 10GB
  jobs:
  - name: postgres
    release: osb-bosh-postgresql
  - name: backup-agent
    release: osb-bosh-postgresql
  - name: postgres_exporter
    release: prometheus
    properties:
  properties:
    postgres_exporter:
      datasource_name: "postgresql://((exporter_credentials.username)):((exporter_credentials.password))@127.0.0.1:6432/postgres?sslmode=disable"
    backup_agent:
      username: backup
      password: rulez
    postgres:
      resource:
        shared_buffers: 128MB
        temp_buffers: 8MB
        encoding:
          lc_messages: 'en_US.UTF-8'
          lc_monetary: 'en_US.UTF-8'
          lc_numeric:  'en_US.UTF-8'
          lc_time:     'en_US.UTF-8'
      config:
        port: 5432
        max_connections: 400
        max_files_per_process: 1000
        shared_preload_libraries: 'pg_stat_statements'
      archive_cleanup:
        threshold: 10
      hba:
        - host all all 0.0.0.0/0 md5
        - host all all ::/0 md5
      replication:
        archive_mode: 'on'
        enabled: true
        password: replication_rulez
      admin_users:
      - username: admin
        password: rulez
        admin: true
      - username: exporter
        password: rulez
        admin: false
      backup_users:
      - username: backup
        password: rulez
      users:
      - username: sample
        password: rulez
        admin: true
      databases:
      - name: sample
        users:
        - sample
        extensions:
        - citext

- name: pgpool
  instances: 1
  vm_type: minimal
  stemcell: default
  azs:
  - z1
  networks:
  - name: service
  jobs:
  - name: pgpool
    release: osb-bosh-postgresql
  properties:
    pcp:
      system_password: ((pcp_password))
    pgpool:
      pool_passwd: pool_passwd
      debug: on
      backend:
        port: 5432
      max_pool: 4
      num_init_children: 32
      enable_pool_hba: on
      load_balance_mode: off
      master_slave_mode: on
      master_slave_sub_mode: stream
      client_idle_limit: 10
      connection_life_time: 10
      hba:
      - host all all 0.0.0.0/0 md5
      - host all all ::/0 md5
