---
# https://bosh.io/docs/cli-v2.html#deployment-mgmt

name: osb-bosh-postgresql

releases:
- name: osb-bosh-postgresql
  version: latest
- name: osb-bosh-monitoring
  version: latest

update:
  canaries: 1
  max_in_flight: 2
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

instance_groups:
- name: postgres
  instances: 2
  vm_type: small
  stemcell: default
  azs:
  - z1
  networks:
  - name: service
  persistent_disk_type: 10GB
  jobs:
  - name: postgres
    release: osb-bosh-postgresql
  - name: backup-agent
    release: osb-bosh-postgresql
  - name: node_exporter
    release: osb-bosh-monitoring
  - name: postgres_exporter
    release: osb-bosh-monitoring
  properties:
    backup_agent:
      user: "backup"
      password: "rulez"
    postgres_exporter:
      user: admin
      password: admin
      port: 5432
    postgres:
      config:
        port: 5432
        max_connections: 500
        shared_buffers: 128MB
        temp_buffers: 8MB
        max_files_per_process: 1000
        lc_messages: 'en_US.UTF-8'
        lc_monetary: 'en_US.UTF-8'
        lc_numeric:  'en_US.UTF-8'
        lc_time:     'en_US.UTF-8'
        shared_preload_libraries: 'pg_stat_statements'
      hba:
      - host all all 0.0.0.0/0 md5
      - host all all ::/0 md5
      replication:
        enabled: true
      databases:
      - name: admin
        users:
        - admin
      users:
      - username: admin
        password: admin
        admin: true

- name: pgpool
  instances: 1
  vm_type: minimal
  stemcell: default
  azs:
  - z1
  networks:
  - name: service
  jobs:
  - name: pgpool
    release: osb-bosh-postgresql
  - name: node_exporter
    release: osb-bosh-monitoring
  properties:
    pcp:
      system_password: secret
    pgpool:
      pool_passwd: pool_passwd
      debug: false
      backend:
        port: 5432
      config:
        init_max_childen: 250
        enable_pool_hba: on
        port: 5432
      hba:
      - host all all 0.0.0.0/0 md5
      - host all all ::/0 md5
      users:
      - username: admin
        password: admin
        admin: true
